name: PR Notification to Discord

on:
  pull_request:
    types: [opened]

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: benc-uk/workflow-discord-webhook@v2
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: |
            ðŸš€ **New Pull Request Created!**
            **Title:** ${{ github.event.pull_request.title }}
            **Author:** ${{ github.event.pull_request.user.login }}
            **URL:** ${{ github.event.pull_request.html_url }}
